### ISSUE TITLE
Consider separating MySQL from the Container

### ISSUE THREAD

**Issue by rclayton-the-terrible** [crramirez/limesurvey#1]
First of all, thank you for your work on this image.  I was wondering if you considered separating MySQL from the image and instead spun up MySQL via Docker Compose and linking the container?  

Since everything is bundled in this one container I can't use it for a production deployment (which I'll be backing with an RDS instance.  So, I'm left with essentially copying your Dockerfile, but rooting it on the php:apache image.

**Comment by crramirez** [comment]
Sounds good. Let me think how it can be accomplished. I never though in that because I didn't consider the RDS scenario.

**Comment by crramirez** [comment]
Hello,

After a while I investigated enough this issue and its motivation. 

Despite the included MySQL in the container, the user can always connect to an external database just typing the right parameters in the **Database configuration** page.

The problem of course is to have an included mysql running. I now know where the change can be made to the parent container so the included MySQL won't run. I am thinking in adding an environment variable to avoid the included MySQL from running. It will also work for the docker compose scenario.

You may ask. But why you don't simply point the Dockerfile to php:apache? Simplicity. This container have many users and I am sure at least some of them prefer just one `docker run` and don't deal with container linking or install another database. But if they want to, we need to provide a way of  doing it.

I am thinking also update the readme page remembering tat despite the included MySQL, the user have freedom for using anothe database. Also I will update the Dockerfile so PostgreSQL will be supported as well. Although I can add Sql Server as well it will be the first option in configuraiton page and the users will be confused a bit.

Regards

**Comment by rclayton-the-terrible** [comment]
@crramirez We ended up forking the deployment and doing exactly what you said (configuring Limesurvey to connect to the external DB).  We unfortunately still use the LAMP image as the base, largely because installing all of the dependencies from php:apache was a nightmare (we're a Node.js team so this was a task beyond us).  We also use an external MySQL instance in development, started and linked via Docker Compose.  This was largely because we wanted to store MySQL bootstrap scripts for Limesurvey in version control -- we also maintain the Database storage as an external volume.  If you're interested in any of that code, let me know.

**Comment by leonhooijer** [comment]
Fixed with #7?

**Comment by crramirez** [comment]
And with this? https://github.com/crramirez/limesurvey/commit/1b00647320350d2da2816b6719504f0d0b4188a7

**Comment by clingeric** [comment]
@rclayton-the-terrible I know this over a year old, but I'd love to take a look at that code to attach an external MySQL database. 

Thanks

**Comment by crramirez** [comment]
Hello @rclayton-the-terrible just configure the external database in Limesurvey setup page. You don't need to do anything at the container side. Pass -e DISABLE_MYSQL=yes in docker run to disable the built in MySQL Database

**Comment by rclayton-the-terrible** [comment]
@clingeric unfortunately, I left the company that I did this work at and don't have access to that code anymore.  Maybe @coxsone can help?

**Comment by crramirez** [comment]
Ok I don't have idea what you two are talking about
