### ISSUE TITLE
Web app does not work behind a proxy

### ISSUE THREAD

**Issue by yurivanmidden** [crramirez/limesurvey#11]
My server is using multiple web applications and thus this docker is used behind a proxy. However when the Limesurvey server is called, the url is rewritten to the internal Docker hostname, which is generally not exposed to the outside world.
Can you add a environment variable for baseUrl, so that rewriting is turned off?

![image](https://cloud.githubusercontent.com/assets/6409975/24358722/58355448-1302-11e7-8a98-481068fb659d.png)

**Comment by yurivanmidden** [comment]
This was an error of mine in the PorxyPass configuration. Should have left ':80' out

**Comment by crramirez** [comment]
Well this is an use case that I haven't tested. Glad it worked for you.
