### ISSUE TITLE
default mysql password

### ISSUE THREAD

**Issue by opensamba** [crramirez/limesurvey#14]
Hi,
what is the root default password if not set for the mysql db ?

**Comment by crramirez** [comment]
Hello,

The first time you run the container it shows the following information in the console:
```
=> An empty or uninitialized MySQL volume is detected in /var/lib/mysql
=> Installing MySQL ...
=> Done!
=> Waiting for confirmation of MySQL service startup
=> Creating MySQL admin user with random password
=> Done!
========================================================================
You can now connect to this MySQL Server using:
mysql -uadmin -pDQ1ZFODMgJJm -h<host> -P<port>

Please remember to change the above password as soon as possible!
MySQL user 'root' has no password but only allows local connections
 ========================================================================

```

The root user has no password, but only accepts local connections. So you can:

docker exec -u root -it _<containerid>_ bash
Then

mysql Enter

You will be in mysql as root, and then you can change the password if you wish.

Regards

**Comment by opensamba** [comment]
thanks, I think this could be documented in the wiki for backup purpose

**Comment by crramirez** [comment]
I agree
