### ISSUE TITLE
bug(docker): Returns to installation when container restarts

### ISSUE THREAD

**Issue by arneschreuder** [crramirez/limesurvey#15]
Upon deployment, when a node restarts, the docker container gets started up again, taking the user through the installation process all over again.

No data is lost,  but you have to re-enter database details again. 

Have not tested with:

* External DB

**Comment by crramirez** [comment]
Check if when your node restarts it uses `docker run` instead of `docker start`. Probably you put `docker run` in a startup script.

**Comment by arneschreuder** [comment]
@crramirez we deployed using Docker Swarm, which has by default a restart-policy.

**Comment by ThEWiZ76** [comment]
Simply map the config file to a persistent file. For example add this:

`-v /var/lib/docker/volumes/limesurvey-config/config.php:/var/www/html/application/config/config.php`

I create the file at forehand, making sure it has the correct config that reflects my environment.

**Comment by arneschreuder** [comment]
This should work. Thanx
