### ISSUE TITLE
Error 500 Serveur script Php

### ISSUE THREAD

**Issue by sebabal1** [crramirez/limesurvey#17]
Hello, I made a script which allows to get back the key of session thanks to the API of Limesurvey. But concerns is that when I launch the container and what I launch my script which is in the root. I receive the error 500 at the level of the server is it possible to have a help thank you

**Comment by crramirez** [comment]
Hello

Attach the script to check it

Regards

**Comment by sebabal1** [comment]
<?php

require_once 'application/libraries/jsonRPCClient.php';

define( 'LS_BASEURL', 'http://localhost:8001/');  // adjust this one to your actual LimeSurvey URL
define( 'LS_USER', 'admin' );
define( 'LS_PASSWORD', '1234' );
$myJSONRPCClient = new JsonRPCClient( LS_BASEURL.'/admin/remotecontrol' );

$sessionKey= $myJSONRPCClient->get_session_key( LS_USER, LS_PASSWORD );
echo 'Hello world';
?>

I have copy this script in /var/www/html/ in the container of limesurvey. And when I try to launch it I have error 500 and I try to fix it 

Thanks for your help

**Comment by sebabal1** [comment]
It's this script work crramirez ? Or have you the same problem as like me ?

**Comment by crramirez** [comment]
How do you execute this script?

**Comment by sebabal1** [comment]
I enter localhost:8001/limesurvey/limesurvey/test.php
8001 is the port that I attribute to the docker container
and test.php is the script of the code that we can seen before 

Do you want other information ? 

Thanks for your reply

**Comment by crramirez** [comment]
I don't really understand your script and I am not able to run it. But if your script runs inside the container you should change:

define( 'LS_BASEURL', 'http://localhost:8001/'); // adjust this one to your actual LimeSurvey URL

by 

define( 'LS_BASEURL', 'http://localhost:80/'); // adjust this one to your actual LimeSurvey URL

**Comment by crramirez** [comment]
I close it because it is not related to the container
