### ISSUE TITLE
Update request

### ISSUE THREAD

**Issue by alanlun516** [crramirez/limesurvey#20]
Dear Admin,
  Shall we update to [limesurvey3.13.2+180709](https://www.limesurvey.org/stable-release)?
Best,
Alan

**Comment by crramirez** [comment]
Yes I am working on that. Probably for the next week.

Regards

**Comment by alanlun516** [comment]
Dear @crramirez ,

  Thanks for your prompt reply.
  Your efficient and excellent works are appreciated.

Best,
Alan

**Comment by crramirez** [comment]
Hello,

Please check the release:

https://github.com/crramirez/limesurvey/releases/tag/3.14.3 

Or

docker pull crramirez/limesurvey:3.14.3

Upload is not working yet, probably I need to adjust the htaccess file. 

PLEASE do not upgrade a production environment without backing up and this is a pre release, don't use it in a production environment.

Please test and tell me if you find something

Regards,
Carlos
