### ISSUE TITLE
localhost as database

### ISSUE THREAD

**Issue by dmenne** [crramirez/limesurvey#24]
Containers with MySQL and Postgresql are running fine, but in database configuration I always get "connection failed". 

-- database location localhost
-- database user postgres
-- database password limesurvey

**Comment by dmenne** [comment]
Maybe add to documentations?

    docker inspect limesurvey_pgsql_1 | grep IPAddress

**Comment by crramirez** [comment]
Hello,

Are you using thie docker-compose yml ? `docker-compose.pgsql.yml`

Regards

**Comment by dmenne** [comment]
Yes, or the MySQL alternative.

**Comment by crramirez** [comment]
I recommend to use 

-- database location mysql

or

-- databse location pgsql

Instead of the IP from docker inspect. It is more reusable.

I agree it needs to be added to the documentation

**Comment by crramirez** [comment]
@dmenne Check this please:

https://github.com/crramirez/limesurvey/pull/25/commits/593ec476fd8c6c02102b96783ab1a886ce514f45

**Comment by dmenne** [comment]
Fine. Thanks!
