### ISSUE TITLE
Alias for different location

### ISSUE THREAD

**Issue by joerg** [crramirez/limesurvey#3]
Hi,

I was struggling with getting this to work on a different location than /, like https://domain.com/survey. In the end I had to add an Alias to the apache config:

```
<VirtualHost *:*>
        ServerAdmin webmaster@localhost

        Alias /${HTTP_LOCATION} /var/www/html
        DocumentRoot /var/www/html
...
```

And then pass an environment variable HTTP_LOCATION to the container. If none is given it works just like always.

Would be great if you add this to the next release. If you prefer a pull request I'll also be happy to provide one.

**Comment by crramirez** [comment]
Hello,

Well I am very short of time. So if you can make a push request it would be great!

Thank you

**Comment by joerg** [comment]
No Problem. Should I also include an update to the latest version? We are running it since this morning and it seems to work fine.

**Comment by crramirez** [comment]
Great!!
