### ISSUE TITLE
session.save_path: /var/lib/php5

### ISSUE THREAD

**Issue by VolodymyrBiryuk** [crramirez/limesurvey#33]
Installation process stuck in Pre-installation check

![Screenshot 2019-07-15 at 16 36 46](https://user-images.githubusercontent.com/19716910/61224457-e71ff700-a71e-11e9-8a9e-7c4713b55e04.png)

**Comment by crramirez** [comment]
Hello,

I will try to reproduce it

Thanks

**Comment by pRot0ta1p** [comment]
Same issue here, 
OS: Debian Debian 4.19.37-5+deb10u2 (2019-08-08) x86_64 GNU/Linux
docker version:
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:21:24 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:56 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

![ttttt](https://user-images.githubusercontent.com/37837882/63651954-eef6a080-c78c-11e9-83ca-9a90d40d53e0.PNG)

**Comment by pRot0ta1p** [comment]
alright so clean the browser cache & cookie the restart it solve the problem,, 🤣 , there are session files exist in /var/lib/php5, so session is writable. just a firefox bug

**Comment by crramirez** [comment]
Very good :)

**Comment by VolodymyrBiryuk** [comment]
> alright so clean the browser cache & cookie the restart it solve the problem,, 🤣 , there are session files exist in /var/lib/php5, so session is writable. just a firefox bug

This worked indeed.

**Comment by marouane1206** [comment]
Facing the same issue while trying to install V4 on PHP 7.2. I've cleaned the browser cache and cookies and the problem is still there. Using chrome.
