### ISSUE TITLE
PHP PDO driver library None found&PHP/PECL JSON library with ！mark

### ISSUE THREAD

**Issue by xuefeng-hao** [crramirez/limesurvey#44]
Hi, when I  run following command in CentOS 
docker run -d --name limesurvey -v $(pwd)/lim_upload:/app/upload -v $(pwd)/lim_etc_php5:/etc/php5 -v $(pwd)/lim_mysql:/var/lib/mysql -p 80:80 crramirez/limesurvey:latest

I got the error in 3. step Pre-installation check:
1. PHP PDO driver library None found
2. PHP/PECL JSON library with a ！mark

also with several! marks PHP GD library&PHP LDAP library&PHP imap library in Optional modules.

I want to check the php.ini in docker to give the "extension=php_pdo.dll" under the construction from the Internet, but I didn’t find the file.

could you please give a hint of this Error? Thanks

**Comment by crramirez** [comment]
Hello @xuefeng-hao,

Which is the reason for this host mount: -v $(pwd)/lim_etc_php5:/etc/php5 ? You are overwriting the default configuration hence the missing modules. The php.ini that it is using is inside due to the override.

Regards,
Carlos

**Comment by xuefeng-hao** [comment]
> Hello @xuefeng-hao,
> 
> Which is the reason for this host mount: -v $(pwd)/lim_etc_php5:/etc/php5 ? You are overwriting the default configuration hence the missing modules. The php.ini that it is using is inside due to the override.
> 
> Regards,
> Carlos

Hi carlos,

Thanks for your quick and nice reply, it works for me now when I abandon the mount line! yes, I was trying to sync the php5 to my local host, looks like not a good idea.

but i got one more new Error, which is the only one with ! mark:
Session writable:  session.save_path: /var/lib/php5
I think change it to 777 is not a good choice, do you have any suggestions, should I change the group or owner to which user?

Thanks! xuefeng

**Comment by xuefeng-hao** [comment]
> > Hello @xuefeng-hao,
> > Which is the reason for this host mount: -v $(pwd)/lim_etc_php5:/etc/php5 ? You are overwriting the default configuration hence the missing modules. The php.ini that it is using is inside due to the override.
> > Regards,
> > Carlos
> 
> Hi carlos,
> 
> Thanks for your quick and nice reply, it works for me now when I abandon the mount line! yes, I was trying to sync the php5 to my local host, looks like not a good idea.
> 
> but i got one more new Error, which is the only one with ! mark:
> Session writable: session.save_path: /var/lib/php5
> I think change it to 777 is not a good choice, do you have any suggestions, should I change the group or owner to which user?
> 
> Thanks! xuefeng

sorry, after "check again " it works now.
